---
title: ⭐⭐⭐ Parametrise your report
subtitle: 📋 Instructions
author:
  - name:
      given: Hélène
      family: Langet
    affiliations:
      - name: Swiss TPH Research-IT
    orcid: 0000-0002-6758-2397
    email: helene.langet@swisstph.ch
license: "CC-BY"
date: last-modified
editor: source
lang: en-US

format:
  html:
    default: true
    embed-resources: true
    code-link: true
    theme: cosmo
    toc: true
    number-sections: true
    anchor-sections: true
    title-block-banner: true
    comments:
      hypothesis: 
        theme: classic
    other-links:
      - text: df1.RData
        href: df1.RData
      - text: df2.RData
        href: df2.RData
    code-links:
      - text: exercise3.qmd
        icon: file-code
        href: https://github.com/Research-IT-Swiss-TPH/quarto_training/blob/main/practicals/exercise3.qmd
    format-links: [pdf]
  pdf:
    default: true
    toc: true
    number-sections: true
  revealjs:
    default: true
    number-sections: true
    output-file: exercise3_instructions_slides.html
    code-overflow: wrap
    embed-resources: true
    logo: ../images/swisstph_logo_compact.png
    css: ../css/logo.css
    footer: "Swiss TPH, Research-IT"
    smaller: true
    slide-number: true
    show-slide-number: all
    
execute:
  echo: fenced
  warning: false
    
resources:
  - exercise5_instructions.pdf
  - df1.RData
  - df2.RData
---

## 🎯 Exercise objectives

-   This exercise builds on the previous exercises where you learnt to [create a simple MS Word report ⭐](./exercise3_instructions.html) and to [add dynamic elements to your report ⭐⭐](./exercise4_instructions.html). Mastering these two exercises is essential for successfully completing this one;
-   Open your modified Quarto document `exercise4.qmd` in RStudio;
-   All text formatted in bold is a placeholder and should be replaced with appropriate automated calculations or cross-references;
-   Complete each of the following tasks and render the document after each task or set of tasks to track your progress.

## Parametrise your report

::: callout-tip
-   See [Quarto documentation about parameters](https://quarto.org/docs/computations/parameters.html#knitr)
-   See [Quarto documentation about rendering outputs using different parameters](https://quarto.org/docs/computations/parameters.html#rendering)
:::

-   [ ] Adjust the report to focus on data for the year 2022 only ;
-   [ ] You were unfortunately provided with a previous erroneous version of the dataset. Update the report to use the dataset stored in `df2.RData` instead of the one stored in `df1.RData` ;
-   [ ] Render 3 reports (1 report with df2.RData for the full outbreak period, 1 report with df1.RData for year 2021 only, 1 report with df2.RData for year 2021 only) adapting the following command which needs to be run in a terminal (ensure your working directory is the one where your Quarto document is stored and all file paths are correct).

```         
quarto render exercise3.qmd --out report_data1.docx -P dataset:df1.RData
```

::: callout-important
### Discussion question

Discuss the advantages and disadvantages of using R within Quarto compared to using R scripts.
:::

## Finalise your MS Word report

::: callout-tip
See [Quarto documentation about Word templates](https://quarto.org/docs/output-formats/ms-word-templates.html)
:::

-   [ ] Apply the Swiss TPH template `swisstph_template.docx` to your MS Word rendered report ;
-   [ ] Create your own template and apply it to your MS Word rendered report.