---
title: "Quarto training for R - Exercise 3"
author:
  - name: Helene Langet
    email: helene.langet@swisstph.ch
    affiliations:
      - name: Research-IT, Swiss TPH
format: docx
editor: visual
---

## Customise the Word document

If you want to customize the appearance of MS Word output, Pandoc supports a special type of template called a reference document. Here’s an example of specifying a custom reference document for docx:

format:
  docx:
    reference-doc: custom-reference-doc.docx

Reference documents include sample text that uses all of the output styles used by Pandoc.

To use a reference doc template, just copy it to your document’s directory and reference it as shown above.

### Task 1

Add a table of content

You can use a table of contents and/or section numbering to make it easier for readers to navigate your document. Do this by adding the toc and/or number-sections options to document options. Note that these options are typically specified at the root level because they are shared across all formats.

## Task 2 - Customize the template

https://quarto.org/docs/output-formats/ms-word-templates.html

## Task 3 - Add caption

## Use parameters