---
title: "Synthetic dataset generation"
format: html
---

```{r}
library(ggplot2)
library(dplyr)
library(lubridate)
```

```{r}
generator <- function(start_date,
                      end_date,
                      n,
                      percentage_confirmed = 0.85,
                      percentage_death = 0.15,
                      max_disease_effect = 0.6,
                      max_age_effect = 0.03,
                      max_bmi_effect = 0.05) {
  
  # Set the seed for reproducibility
  set.seed(123)
  
  dates <- seq.Date(start_date, end_date, by = "day")
  
  # Randomly sample n dates from the range for individual cases
  sampled_dates <- sample(dates, n, replace = TRUE)
  
  # Generate ConfirmedCases column (1 = confirmed, 0 = not confirmed) based on the percentage
  confirmed <- rbinom(n, 1, percentage_confirmed)
  
  # Generate ConfirmedDeaths column (1 = death, 0 = no death) based on the percentage
  #death <- rbinom(n, 1, percentage_death)
  
  # Generate age and weight
  # Assume age ranges from 20 to 80 and weight ranges from 50 to 100 kg
  age <- sample(20:80, n, replace = TRUE)
  # Assume height ranges from 150 to 200 cm and weight ranges from 50 to 100 kg
  height <- sample(150:200, n, replace = TRUE) # height in cm
  weight <- sample(40:140, n, replace = TRUE)   # weight in kg
  
  # Calculate BMI: BMI = weight (kg) / (height (m))^2
  height_m <- height / 100  # Convert height to meters
  bmi <- weight / (height_m^2)
  
  disease_effect <- runif(n, min = 0, max = max_disease_effect)
  age_effect <- runif(n, min = 0, max = max_age_effect)
  bmi_effect <- runif(n, min = 0, max = max_bmi_effect)
  
  # Adjust age and weight to be correlated with death
  # Higher age and weight might be correlated with a higher probability of death
  # Create a logistic model to simulate this correlation
  death_probability <- plogis(disease_effect * 30 * (confirmed - 0.5)) * plogis(age_effect * (age - 50) + bmi_effect * (bmi - 25))
  death <- rbinom(n, 1, death_probability * percentage_death)
  
  # Create a data frame with the generated data (individual case reports)
  df <- data.frame(
    id        = 1:n,
    age       = age,
    bmi       = bmi,
    date      = sampled_dates,
    confirmed = confirmed,
    death     = death
  )
  
}
```

```{r}
start_date_all <- as.Date("2021-01-01")
end_date <- as.Date("2021-03-31")
n <- 10132
percentage_confirmed <- 0.85
percentage_death <- 0.06 
max_disease_effect <- 0.96
max_age_effect <- 0.03
max_bmi_effect <- 0.6
sdf1 <- generator(start_date_all, end_date, n, percentage_confirmed, percentage_death, max_disease_effect, max_age_effect, max_bmi_effect)

start_date <- as.Date("2021-04-01")
end_date <- as.Date("2021-05-10")
n <- 5873
percentage_confirmed <- 0.83
percentage_death <- 0.04
max_disease_effect <- 0.95
max_age_effect <- 0.02
max_bmi_effect <- 0.5
sdf2a <- generator(start_date, end_date, n, percentage_confirmed, percentage_death, max_disease_effect, max_age_effect, max_bmi_effect)

start_date <- as.Date("2021-04-01")
end_date <- as.Date("2021-05-10")
n <- 6525
percentage_confirmed <- 0.82
percentage_death <- 0.07
max_disease_effect <- 0.87
max_age_effect <- 0.1
max_bmi_effect <- 0.5
sdf2b <- generator(start_date, end_date, n, percentage_confirmed, percentage_death, max_disease_effect, max_age_effect, max_bmi_effect)

start_date <- as.Date("2021-05-11")
end_date <- as.Date("2021-09-30")
n <- 12000
percentage_confirmed <- 0.88
percentage_death <- 0.05
max_disease_effect <- 0.92
max_age_effect <- 0.03
max_bmi_effect <- 0.4
sdf3 <- generator(start_date, end_date, n, percentage_confirmed, percentage_death, max_disease_effect, max_age_effect, max_bmi_effect)

start_date <- as.Date("2021-10-01")
end_date <- as.Date("2022-02-28")
n <- 14993
percentage_confirmed <- 0.75
percentage_death <- 0.04
max_disease_effect <- 0.89
max_age_effect <- 0.06
max_bmi_effect <- 0.4
sdf4a <- generator(start_date, end_date, n, percentage_confirmed, percentage_death, max_disease_effect, max_age_effect, max_bmi_effect)

start_date <- as.Date("2021-10-01")
end_date <- as.Date("2022-02-28")
n <- 15308
percentage_confirmed <- 0.77
percentage_death <- 0.04
max_disease_effect <- 0.85
max_age_effect <- 0.08
max_bmi_effect <- 0.3
sdf4b <- generator(start_date, end_date, n, percentage_confirmed, percentage_death, max_disease_effect, max_age_effect, max_bmi_effect)

start_date <- as.Date("2022-03-01")
end_date <- as.Date("2022-06-03")
n <- 14900
percentage_confirmed <- 0.75
percentage_death <- 0.03
max_disease_effect <- 0.84
max_age_effect <- 0.02
max_bmi_effect <- 0.2
sdf5 <- generator(start_date, end_date, n, percentage_confirmed, percentage_death, max_disease_effect, max_age_effect, max_bmi_effect)

start_date <- as.Date("2022-06-04")
end_date <- as.Date("2022-07-31")
n <- 4000
percentage_confirmed <- 0.76
percentage_death <- 0.02
max_disease_effect <- 0.81
max_age_effect <- 0.01
max_bmi_effect <- 0.1
sdf6 <- generator(start_date, end_date, n, percentage_confirmed, percentage_death, max_disease_effect, max_age_effect, max_bmi_effect)

start_date <- as.Date("2022-08-04")
end_date <- as.Date("2022-12-31")
n <- 4000
percentage_confirmed <- 0.72
percentage_death <- 0.01
max_disease_effect <- 0.89
max_age_effect <- 0.02
max_bmi_effect <- 0.1
sdf7 <- generator(start_date, end_date, n, percentage_confirmed, percentage_death, max_disease_effect, max_age_effect, max_bmi_effect)
```

```{r}
df <- sdf1 |>
  dplyr::bind_rows(sdf2a) |>
  dplyr::bind_rows(sdf3) |>
  dplyr::bind_rows(sdf4a) |>
  dplyr::bind_rows(sdf5) |>
  dplyr::bind_rows(sdf6) |>
  dplyr::bind_rows(sdf7) |>
  dplyr::mutate(week = lubridate::floor_date(date, unit = "week")) |>
  dplyr::filter(week >= start_date_all & week <= end_date)
```

```{r}
nrow(df)
save(df, file = "df1.RData")
```

```{r}
# Aggregate the data to get the weekly count of all cases, confirmed cases and deaths
weekly_data <- df |>
  group_by(week) |>
  summarise(count = n(),
            confirmed_count = sum(confirmed),
            death_count = sum(death))

# Plot the weekly cases, confirmed cases and deaths
ggplot(weekly_data, aes(x = week)) +
  geom_line(aes(y = count, color           = "All cases"), size = 1) +
  geom_line(aes(y = confirmed_count, color = "Confirmed cases"), size = 1) +
  geom_line(aes(y = death_count, color     = "Confirmed deaths"), size = 1) +
  labs(title = "Weekly count of all cases, confirmed cases and deaths",
       x = "Week",
       y = "Count",
       color = "Legend") +
  scale_color_manual(values = c("All cases" = "#440e54",
                                "Confirmed cases" = "#f8766d",
                                "Confirmed deaths" = "#128984")) +
  ggplot2::theme_minimal() +
  ggplot2::theme(panel.grid.major.y = ggplot2::element_line(linewidth = 0.5, linetype = "dashed", color = "grey"),
                 panel.grid.minor.y = ggplot2::element_line(linewidth = 0.5, linetype = "dashed", color = "grey"),
                 panel.grid.major.x = ggplot2::element_blank(),
                 panel.grid.minor.x = ggplot2::element_blank())
```

```{r}
df <- sdf1 |>
  dplyr::bind_rows(sdf2b) |>
  dplyr::bind_rows(sdf3) |>
  dplyr::bind_rows(sdf4b) |>
  dplyr::bind_rows(sdf5) |>
  dplyr::bind_rows(sdf6) |>
  dplyr::bind_rows(sdf7) |>
  dplyr::mutate(week = lubridate::floor_date(date, unit = "week")) |>
  dplyr::filter(week >= start_date_all & week <= end_date)
```
```{r}
nrow(df)
save(df, file = "df2.RData")
```

```{r}
# Aggregate the data to get the weekly count of confirmed cases and deaths
weekly_data <- df |>
  group_by(week) |>
  summarise(count = n(),
            confirmed_count = sum(confirmed),
            death_count = sum(death))

# Plot the weekly confirmed cases and deaths
ggplot(weekly_data, aes(x = week)) +
  geom_line(aes(y = count, color           = "All cases"), size = 1) +
  geom_line(aes(y = confirmed_count, color = "Confirmed cases"), size = 1) +
  geom_line(aes(y = death_count, color     = "Confirmed deaths"), size = 1) +
  labs(title = "Weekly count of all cases, confirmed cases and deaths",
       x = "Week",
       y = "Count",
       color = "Legend") +
  scale_color_manual(values = c("All cases" = "#440e54",
                                "Confirmed cases" = "#f8766d",
                                "Confirmed deaths" = "#128984")) +
  theme_minimal()
```

```{r}
#| label: fig-1
#| fig-cap: Weekly count of all cases, confirmed cases and deaths
#| fig-width: 8
#| fig-height: 4
                
# Aggregate the data to get the weekly count of all cases, confirmed cases and deaths
weekly_data <- df |>
  dplyr::group_by(week) |>
  dplyr::summarise(count = dplyr::n(),
                   confirmed_count = sum(confirmed),
                   death_count = sum(death))

# Plot the weekly cases, confirmed cases and deaths
ggplot2::ggplot(weekly_data, ggplot2::aes(x = week)) +
  ggplot2::geom_line(ggplot2::aes(y = count,
                                  color = "All cases"),
                     size = 1) +
  ggplot2::geom_line(ggplot2::aes(y = confirmed_count,
                                  color = "Confirmed cases"),
                     size = 1) +
  ggplot2::geom_line(ggplot2::aes(y = death_count,
                                  color = "Confirmed deaths"),
                     size = 1) +
  ggplot2::labs(x = "Week",
                y = "Count",
                color = "Legend") +
  ggplot2::scale_color_manual(values = c("All cases" = "#440e54",
                                         "Confirmed cases" = "#f8766d",
                                         "Confirmed deaths" = "#128984")) +
  ggplot2::theme_minimal() +
  ggplot2::theme(panel.grid.major.y = ggplot2::element_line(linewidth = 0.5, linetype = "dashed", color = "grey"),
                 panel.grid.minor.y = ggplot2::element_line(linewidth = 0.5, linetype = "dashed", color = "grey"),
                 panel.grid.major.x = ggplot2::element_blank(),
                 panel.grid.minor.x = ggplot2::element_blank())
```